name: Build SCSS

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      v*.*

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install SASS commandline utility
        run: brew install sass/sass/sass
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Compile Compressed SASS
        run: sass main.scss -s compressed -I . > compressed.css
      - name: Compile Expanded SASS
        run: sass main.scss -I . > expanded.css
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with: 
          files: |
            compressed.css
            expanded.css
