name: Build SCSS

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  compile-scss:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install SASS commandline utility
        run: brew install sass/sass/sass
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Compile Compressed SASS
        run: sass main.scss -s compressed -I . > compressed.css
      - name: Compile Expanded SASS
        run: sass main.scss -I . > expanded.css
  publish-release:
    runs-on: ubuntu-latest
    needs: compile-scss
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          files: |
            compressed.css
            expanded.css
